### PR TITLE
BAR editor improvements

### PR DESCRIPTION
**Pull request by Xeeynamo**
Add CLI tool for BAR files, drag&drop support, file extension for any type, fixes when writing back or creating a BAR and reintroduced back the possibility to open other tools from the BAR editor.

### CODE REVIEW

**Comment by kenjiuno** [comment]
OpenKh.Command.Bar

show help:

```bat
H:\Proj\OpenKh\OpenKh.Command.Bar\bin\Debug\netcoreapp3.1>OpenKh.Command.Bar.exe
1.0.0

Usage: OpenKh.Command.Bar [command] [options]

Options:
  --version     Show version information
  -?|-h|--help  Show help information

Commands:
  list          Print content of a BAR file
  pack          Repack a BAR from its project file
  unpack        Unpack the content of a BAR file and generate a project

Run 'OpenKh.Command.Bar [command] -?|-h|--help' for more information about a command.
```

list: Print content of a BAR file

```bat
H:\Proj\OpenKh\OpenKh.Command.Bar\bin\Debug\netcoreapp3.1>OpenKh.Command.Bar.exe list H:\Proj\OpenKh-Game\OpenKh.Game\bin\Debug\netcoreapp3.1\menu\fm\title.2ld
titl, Imgz, 0
titl, Layout, 0
even, Imgz, 0
even, Layout, 0
```

unpack: Unpack the content of a BAR file and generate a project

```bat
H:\Proj\OpenKh\OpenKh.Command.Bar\bin\Debug\netcoreapp3.1>OpenKh.Command.Bar.exe unpack H:\Proj\OpenKh-Game\OpenKh.Game\bin\Debug\netcoreapp3.1\menu\fm\title.2ld -o .
```

files done by unpack at folder `-o <folder>`:

```
        546 title.2ld.json
  1,152,928 titl.imz
     77,400 titl.layout
  3,398,256 even.imz
     18,908 even.layout
```

title.2ld.json

```title.2ld.json
{
  "OriginalFileName": "title.2ld",
  "Entries": [
    {
      "FileName": "titl.imz",
      "InternalName": "titl",
      "TypeId": 29,
      "LinkIndex": 0
    },
    {
      "FileName": "titl.layout",
      "InternalName": "titl",
      "TypeId": 28,
      "LinkIndex": 0
    },
    {
      "FileName": "even.imz",
      "InternalName": "even",
      "TypeId": 29,
      "LinkIndex": 0
    },
    {
      "FileName": "even.layout",
      "InternalName": "even",
      "TypeId": 28,
      "LinkIndex": 0
    }
  ]
}
```

pack: Repack a BAR from its project file

```bat
H:\Proj\OpenKh\OpenKh.Command.Bar\bin\Debug\netcoreapp3.1>OpenKh.Command.Bar.exe pack title.2ld.json -o "H:\Proj\pcsx2\bin\inject.f266b00b\menu\fm\title.2ld"
```

OpenKh.Command.Bar is good 👍

**Comment by kenjiuno** [comment]
OpenKh.Tools.BarEditor

2020-05-24_11h14_52

When opening existing item from bar file: Does this means we need `OpenKh.Tools.ImageViewer.exe` in same folder as `OpenKh.Tools.BarEditor.exe` is placed?

2020-05-24_11h16_30

When saving bar file having dummy entry with unexpected index (like 100) causes app crash and save file damaged.

2020-05-24_11h19_16

2020-05-24_11h21_29

It will be more safe if it can use buffering technique.

**Comment by Xeeynamo** [comment]
> When opening existing item from bar file: Does this means we need OpenKh.Tools.ImageViewer.exe in same folder as OpenKh.Tools.BarEditor.exe is placed?

Exactly. I did not wanted to create a direct dependency, so the application just scan whenever there is the tool and use it.
But I just found that the functionality is now broken (again) for applications compiled in .NET Core.

> When saving bar file having dummy entry with unexpected index (like 100) causes app crash and save file damaged.
I think it was happening before as well. How "Index" works is that it is assigned an `1` when a file is already found in the BAR. You would need a `zipf` of the same type and index `0` to save it successfully: https://openkh.dev/kh2/file/type/bar#bar-entry

But I agree that the tool needs some kind of user-friendly error. Thanks for noticing that.

**Comment by kenjiuno** [comment]
Thanks for reply!

> Exactly. I did not wanted to create a direct dependency, so the application just scan whenever there is the tool and use it.

Ok I understood!

> I think it was happening before as well. How "Index" works is that it is assigned an `1` when a file is already found in the BAR. You would need a `zipf` of the same type and index `0` to save it successfully: https://openkh.dev/kh2/file/type/bar#bar-entry
> 
> But I agree that the tool needs some kind of user-friendly error. Thanks for noticing that.

I see, I will write pull request for this!

**Comment by kenjiuno** [comment]
> But I just found that the functionality is now broken (again) for applications compiled in .NET Core.

Although Changing `.exe` to `.dll` will resolve `Bad IL Format` error, another error is raised `Clould not load or assembly 'Xe.Drawing.Direct3D, ...'`

```cs
			var toolModule = Plugins
				.GetModules<IToolModule<ToolInvokeDesc>>(null, x => x.Contains(name) && Path.GetExtension(x) == ".dll")
				.FirstOrDefault();
```

2020-05-24_22h36_13

Here are some hits from google:

Create a .NET Core application with plugins
https://docs.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support

.NET Core Plugins
Introducing an API for loading .dll files (and their dependencies) as 'plugins'
https://natemcmaster.com/blog/2018/07/25/netcore-plugins/

**Comment by Xeeynamo** [comment]
That is a very good amount of useful information. I will keep an eye on it and fix the implementation!

**Pull request merged**
