### PR TITLE
New 2ld and 2dd editor

### PR DESCRIPTION
**Pull request by Xeeynamo**
Introduces the new `OpenKh.Tools.LayoutEditor`, which replaces the obsolete `OpenKh.Tools.LayoutViewer`.

The code is still very work in progress and far from complete. But the tool is already working and it is able to open 2dd files, modify them and save them back. It uses the same rendering engine of `OpenKh.Game`.

Please write down any bug or suggestion to improve it before merging. Also please, be totally free to pull the code from the branch and directly apply changes whenever you see a room of improvement.

Tracked bug and improvements so far by @Vladabdf :
- [X] The "Do not loop" checkbox enables itself occasionally. It seems to be random but I didn't test it extensively.
- [X] Allow the user to set a custom background color.
- [ ] Possibly even a simple checkerboard pattern if they wish.
- [X] Labeling the axes for the cropping in the sprite editor would be helpful.
- [X] Adding a "Previous Sprite" and "Next Sprite" button in the sprite editor would make cycling through the sprites faster.
- [ ] Add an "Animation speed" setting in % next to the Animation Group selector, and possibly a frame-by-frame button as well.
- [X] Add an info box that appears for every known variable.
- [X] Crashes consistently caused by saving
- [ ] Being able to zoom in and out from the viewport
- [x] The orbs surrounding Drive numbers in field2d/jp/XX0field.2dd files are not animating properly in the editor.
- [x] Figure out a way where to spawn a sub-sequence when editing a Layout

### CODE REVIEW

**Comment by Vladabdf** [comment]
**Bugs**
- The "Do not loop" checkbox enables itself occasionally. It seems to be random but I didn't test it extensively.

**Adjustments**
- Allow the user to set a custom background color, possibly even a simple checkerboard pattern if they wish. I find it easier to work on darker pastel colors like #306270, but everyone has their preferences. This would be extremely beneficial to the end user!
- Labeling the axes for the cropping in the sprite editor would be helpful.
- Adding a "Previous Sprite" and "Next Sprite" button in the sprite editor would make cycling through the sprites faster.
- Add an "Animation speed" setting in % next to the Animation Group selector, and possibly a frame-by-frame button as well.
- Add an info box that appears for every known variable. For example, when the user holds the mouse over the "Loop frame" text, display a tiny window that explains what that variable does. (I would be more than happy to provide all of these explanations!)

Lastly, I threw together a very quick and somewhat sloppy [mock up](https://i.vgy.me/694lnZ.png) the additions I'd like to see in the sprite editor.

So far I've been enjoying this eye candy and I'll report back later after I play with it some more! This is very exciting.

**Comment by Vladabdf** [comment]
Crashes consistently caused by saving. Does not matter if I use "Save" or "Save as" command, and it happens whether I make changes or leave the file untouched.
image

**Comment by Vladabdf** [comment]
Being able to zoom in and out from the viewport (preferably with the mouse wheel) and move it around so things shown off-screen can be seen would be awesome too!
image

P.S. This is an amazing and powerful editor. I love where it's going so far. Keep up the great work and I'll keep providing feedback as I play around with it!

**Comment by Xeeynamo** [comment]
which file is the one that shows the "item get" animation?

**Comment by Vladabdf** [comment]
XX0field.2dd, though I had to rip out the FIEL and MAPJ IMD/SEQD files within, due to (line 291): 
`            if (sequenceEntries == 0)
                throw new Exception("No sequence found.");
            if (sequenceEntries > 1)
                throw new Exception("Did not expected multiple sequences.");
            var sequenceEntry = entries.First(x => x.Type == Bar.EntryType.Seqd);
            AnimationName = sequenceEntry.Name;

            if (imagesEntries == 0)
                throw new Exception("No image found.");
            if (imagesEntries > 1)
                throw new Exception("Did not expected multiple images for a single sequence.");
            var imageEntry = entries.First(x => x.Type == Bar.EntryType.Imgd);
            TextureName = imageEntry.Name;`

**Comment by Vladabdf** [comment]
Animation rotation is [not showing in the editor](https://cdn.discordapp.com/attachments/575294743852875787/730517305812975688/2020-07-08_16-15-41_pn.gif) + changing default values [causes them to not work at all in-game](https://cdn.discordapp.com/attachments/575294743852875787/730517798618398821/2020-07-08_16-18-23_pn.gif).

**Comment by Xeeynamo** [comment]
> Animation rotation is [not showing in the editor](https://cdn.discordapp.com/attachments/575294743852875787/730517305812975688/2020-07-08_16-15-41_pn.gif) + changing default values [causes them to not work at all in-game](https://cdn.discordapp.com/attachments/575294743852875787/730517798618398821/2020-07-08_16-18-23_pn.gif).

Fixed :)

**Comment by Vladabdf** [comment]
I have no idea what unknown value it could be, but [the orbs](https://i.vgy.me/b7IBkd.gif) surrounding Drive numbers in field2d/jp/XX0field.2dd files are not animating properly in the editor.

**Comment by Vladabdf** [comment]
4bpp images are read in the wrong order, as discoverd by Mr. Kenjiuno. #164 
2020-07-18_16-18-13 OpenKh Tools LayoutEditor_2

**Comment by kenjiuno** [comment]
> 4bpp images are read in the wrong order, as discoverd by Mr. Kenjiuno. #164

@Vladabdf 
Ah, sorry. It is problem of `OpenKh.Command.ImgTool`. It is not problem of LayoutEditor.

`OpenKh.Command.ImgTool` generated wrong 4-bpp imd/imz file. It is what `Incorrect` shows.

To fix the `Incorrect` bitmap, please try one of following method:

- Re-generate imd/imz with fixed `OpenKh.Command.ImgTool`.
- `OpenKh.Command.ImgTool` `swap-imz-pixel` command to swap pixel-order of 4-bpp bitmap.

**Comment by Vladabdf** [comment]
The image I provided is from the fixed ImgTool. I used the `swap-imz-pixel` argument already and it displays correctly in the game and older editors/viewers, but not in OpenKH viewers unfortunately.

image

**Comment by kenjiuno** [comment]
> The image I provided is from the fixed ImgTool. I used the swap-imz-pixel argument already and it displays correctly in the game and older editors/viewers, but not in OpenKH viewers unfortunately.

Ok, I'll check it again!

**Comment by Vladabdf** [comment]
Fixed with #166 thanks again to Mr. Kenjiuno.

**Comment by Xeeynamo** [comment]
Ugh... So I guess that OpenKH displays 4bpp images in the wrong order.
Does the Image Viewer displays images accurately? Are only Game and LayoutEditor "broken"?

**Comment by Vladabdf** [comment]
Yes, as of #166 , all viewers and editors show everything properly and exactly as the game does.

**Comment by Xeeynamo** [comment]
As the Layout Viewer is right now (it's broken at the moment, but see on `master`), do you think it make sense to keep it alive or can we kill it?

**Comment by Vladabdf** [comment]
The editor (this tool) can already view everything that the viewer can, and more; No reason to keep both.

**Comment by Xeeynamo** [comment]
> I have no idea what unknown value it could be (if any), but [the orbs](https://i.vgy.me/b7IBkd.gif) surrounding Drive numbers in field2d/jp/XX0field.2dd files are not animating properly in the editor.
> They should be revolving around the number. The animation layers show up properly but nothing in particular looks out of place with the values so I'm unsure what to suggest about this.

Fixed!

**Comment by Xeeynamo** [comment]
100 commits. It's feature complete. I am waiting your further testing to see if everything is all right. The major change since your last comment is regarding saving and the support for Re:CoM files.

**Comment by Vladabdf** [comment]
The only last thing I would request be added before I merge this PR is, could we get an editor-specific loop function? Explaining in the future tool doc that the "Do not loop" checkbox must be reset to the default state for every animation is going to be painful for everyone involved.

**Comment by Xeeynamo** [comment]
> The only last thing I would request be added before I merge this PR is, could we get an editor-specific loop function? Explaining in the future tool doc that the "Do not loop" checkbox must be reset to the default state for every animation is going to be painful for everyone involved.

I will just create a dedicated button.

**Pull request merged**
