### PR TITLE
Adding OpenKh.Command.ImgTool

### PR DESCRIPTION
**Pull request by kenjiuno**
`OpenKh.Command.ImgTool` can make `.imd` and `.imz` from `.png`, and vice versa. It is useful to make KH2 image files from scratch, for debugging and modding.

```bat
OpenKh.Command.ImgTool.exe
1.0.0

Usage: OpenKh.Command.ImgTool [command] [options]

Options:
  --version     Show version information
  -?|-h|--help  Show help information

Commands:
  imd           png file -> imd file
  imz           png, imd or imz files -> imz file
  unimd         imd file -> png file
  unimz         imz file -> png or imd files

Run 'OpenKh.Command.ImgTool [command] -?|-h|--help' for more information about a command.
```

`imd`

```bat
png file -> imd file

Usage: OpenKh.Command.ImgTool imd [options] <PngFile>

Arguments:
  PngFile                    Input png

Options:
  -?|-h|--help               Show help information
  -o|--output <OUTPUT_IMD>   Output imd. Default is current dir, and file extension to imd.
  -b|--bpp <BITS_PER_PIXEL>  Set bits per pixel: 4, 8, or 32
  -p|--pngquant              Use `pngquant.exe` -- lossy PNG compressor. Download `pngquant.exe` and place it beside
                             this program, current directory, or PATH.
  -n|--nquant                Use embedded nQuant.Core color quantizer. This is default selection.
```

`imz`

```bat
OpenKh.Command.ImgTool.exe imz -h
png, imd or imz files -> imz file

Usage: OpenKh.Command.ImgTool imz [options]

Options:
  -?|-h|--help               Show help information
  -i|--input <INPUT_FILE>    Input png/imd/imz file
  -o|--output <OUTPUT_IMZ>   Output imz file. Default is current dir, and first file extension to imz.
  -b|--bpp <BITS_PER_PIXEL>  Set bits per pixel for every png: 4, 8, or 32
  -p|--pngquant              Use `pngquant.exe` -- lossy PNG compressor. Download `pngquant.exe` and deploy it beside
                             this program, current directory, or PATH.
  -n|--nquant                Use embedded nQuant.Core color quantizer. This is default selection.
  -a|--append                Try to append to imz
```

`unimd`

```bat
OpenKh.Command.ImgTool.exe unimd -h
imd file -> png file

Usage: OpenKh.Command.ImgTool unimd [options] <ImdFile>

Arguments:
  ImdFile                   Input imd

Options:
  -?|-h|--help              Show help information
  -o|--output <OUTPUT_PNG>  Output png. Default is current dir, and file extension to png.
```

`unimz`

```bat
OpenKh.Command.ImgTool.exe unimz -h
imz file -> png or imd files

Usage: OpenKh.Command.ImgTool unimz [options] <ImzFile>

Arguments:
  ImzFile                   Input imz

Options:
  -?|-h|--help              Show help information
  -o|--output <OUTPUT_DIR>  Output dir. Default is current dir.
  -m|--imd                  Export as imd instead of png

```

### CODE REVIEW

**Comment by kenjiuno** [comment]
Thanks for checking! I'll fix it later!

**Comment by Rikux3** [comment]
As i was testing another Pull Request, i've stumbled upon a bug when converting a 32-bit png. It seems that the image is quantized incorrectly? I don't know anything about Imaging, i'm only passing the conversation I had with Vlad and Tom.

Original image
done2.

In Emulator
pcsx2

**Comment by Xeeynamo** [comment]
Converting from png to imd specifying 8bpp and then from imd to png would give the same image? I think it's easier to test rather than checking on the emulator.

Second, the quantization helps for quick testing, but I would not take it as the definitive one when importing PNG files since there are better quantization algorithms that are patented. If someone seek accuracy, I would just suggest to convert the image to 8bpp before performing the conversion with this tool as this will never ever reach the quality of the patented algorithms.

**Comment by kenjiuno** [comment]
Hi thanks for trying this pull request!

> As i was testing another Pull Request, i've stumbled upon a bug when converting a 32-bit png. It seems that the image is quantized incorrectly? I don't know anything about Imaging, i'm only passing the conversation I had with Vlad and Tom.

Yes. My quantization processor is very rough level for now 😓

```
            public PaletteGenerator(List<uint> pixels, int maxColors)
            {
                MostUsedPixels = pixels
                    .GroupBy(pixel => pixel)
                    .OrderByDescending(group => group.Count())
                    .Select(group => group.Key)
                    .Take(maxColors)
                    .ToArray();

            }
```

It is possible that 32bpp → 8bpp conversion will produce the mono tone flavor texture, as you have posted.

I'll find better quantization processor.

**Comment by kenjiuno** [comment]
> Second, the quantization helps for quick testing, but I would not take it as the definitive one when importing PNG files since there are better quantization algorithms that are patented. If someone seek accuracy, I would just suggest to convert the image to 8bpp before performing the conversion with this tool as this will never ever reach the quality of the patented algorithms.

Exactly. Currently 32bpp → 8bpp reduction process is minimal level.
Using another software before making `imd` `imz` is better idea...

Although I'm not really specific about patented algorithm, I want to try some ideas to choice:

- Try `nQuant.Core.dll` as Soraiko's IMAGEEDITOR uses.
- Save as GIF at first (rely on GDI+ quantization). https://stackoverflow.com/a/6356108
- Try to invoke `magick.exe png:- -colors 256 png:-` for color reduction.

**Comment by Xeeynamo** [comment]
Color quantisation it is a very hard problem to solve: https://en.wikipedia.org/wiki/Color_quantization
The patented algorithm I mentioned is the one from Photoshop. I read it in an article long time ago.

If we decide to include it. I would go for a cross-platform solution. Maybe there is a NuGet package for it? Or the GIF solution you proposed sounds reasonable.

Either way, I suggest to let the user know that the quantisation from the tool:
A warning message can be displayed when converting to a lower bpp, or the conversion will be denied unless a flag is specified (eg. `--force`).

Either way, the pull request looks good to me! I accept it, but I will not merge it unless someone else wants to give another proposal or if you think that the warning or the force flag is a good idea.

**Comment by Vladabdf** [comment]
I've used pngquant for years with KH2, and it has given me zero problems. If possible, I would recommend we simply use that. Photoshop uses pngquant as well, seeing as it's in every Photoshop install folder. I imagine including it in our repo, or some variant of it, would be very possible.

**Comment by kenjiuno** [comment]
This compare is using trimmed part of screen shot:

compare


[nQuant](https://archive.codeplex.com/?p=nquant) is impressive.

**Comment by Vladabdf** [comment]
If nQuant is being considered, I would recommend looking at [Crazycatz00's repo](https://github.com/Crazycatz00/nQuant) where he added 1-bit and 4-bit color support, both of which are supported by KH1, KH2, and ReCoM.

**Comment by kenjiuno** [comment]
I have imported `nQuant.Core` from https://github.com/Crazycatz00/nQuant (This nQuant is not on nuget)
ImgTool uses `nQuant.Core` by default. Optionally external `pngquant.exe` can be used if `-p` is given.

`OpenKh.Command.ImgTool.exe imd -p file.png`

Compare:

compare

I see slight differences at gradient fill among nQuant and pngquant outputs.

**Comment by Vladabdf** [comment]
The puzzle isn't complete in this image, but it's confirmed working at last! It works with both nQuant and pngquant images that I tested.
image

**Comment by kenjiuno** [comment]
@Vladabdf Thanks for checking!

The `OpenKh.Command.ImgTool.exe imd -h` help contains a little about `nQuant` and `pngquant`. I believe careful users will understand that description!

```bat
H:\Proj\OpenKh\OpenKh.Command.ImgTool\bin\Debug\netcoreapp3.1>OpenKh.Command.ImgTool.exe imd -h
png file -> imd file

Usage: OpenKh.Command.ImgTool imd [options] <PngFile>

Arguments:
  PngFile                    Input png

Options:
  -?|-h|--help               Show help information
  -o|--output <OUTPUT_IMD>   Output imd. Default is current dir, and file extension to imd.
  -b|--bpp <BITS_PER_PIXEL>  Set bits per pixel: 4, 8, or 32
  -p|--pngquant              Use `pngquant.exe` -- lossy PNG compressor. Download `pngquant.exe` and place it beside
                             this program, current directory, or PATH.
  -n|--nquant                Use embedded nQuant.Core color quantizer. This is default selection.
```

**Pull request merged**
