### PR TITLE
Fix model load

### PR DESCRIPTION
**Pull request by Xeeynamo**
This fixes a couple of bugs that prevent some 3D models to be loaded correctly. This patch will allow to load all of them, regardless their "type".

### CODE REVIEW

**Comment by Vladabdf** [comment]
Certain models appear to crash the game. From what I can tell, it's mostly hi-poly models. Examples being ACTOR-SORA-H and H_PO010. However, P_EX110_BTLF, which is a low-poly model, also crashes the engine. What models do load though, load correctly!
image

**Comment by kenjiuno** [comment]
> Certain models appear to crash the game. From what I can tell, it's mostly hi-poly models. Examples being ACTOR-SORA-H and H_PO010. However, P_EX110_BTLF, which is a low-poly model, also crashes the engine. What models do load though, load correctly!

Oh, it is refactored code that I have pushed around last week. I'll check it later!

**Comment by kenjiuno** [comment]
Ok, ACTOR-SORA-H will be loadable now.

**Comment by Xeeynamo** [comment]
@Vladabdf I confirm that @kenjiuno fixed the issue of loading high poly models!
image

**Pull request merged**
