### PR TITLE
Fix image export in ImageViewer

### LINKED ISSUE #246: Saving as certain formats crashes the image viewer + produces an empty image
The resulting file is 0 bytes in size and contains zero data. This currently happens with TIM2, FAC, IMZ, ARC, and TEX.
I.e., only PNG, BMP, TIFF, and IMD work.
[image exports.zip](https://github.com/Xeeynamo/OpenKh/files/5248522/image.exports.zip)

### PR DESCRIPTION
**Pull request by kenjiuno**
Fix image export in ImageViewer:
- Expand export function: (current image | all images)
- Check `.IsCreationSupported` flag

Edit menu:

2020-10-14_08h16_11-fs8

Current image export (both single image format and container format):

2020-10-14_08h30_33-fs8

All images export (only container format):

2020-10-14_08h19_28-fs8

Fix #246

### CODE REVIEW

**Comment by Vladabdf** [comment]
Saving as IMGD appears to swap color channels. Other formats work well.
image

**Comment by kenjiuno** [comment]
Oh this B⇔R channel swapping problem is serious. I'll check this.

**Comment by Vladabdf** [comment]
As of the latest commit, the B⇔R swap appears to be fixed, however .bmp extraction creates a broken image that crashes the viewer. The image will open with traditional image viewers, but it displays incorrectly.
image

**Comment by Vladabdf** [comment]
For now I'll go ahead and merge this, as every format except bmp works as expected. This is unimportant right now and can be fixed at a later time down the line.

**Review by Vladabdf — APPROVED** [review]

**Pull request merged**
