### PR TITLE
KKDF2 MDLX parser refactor

### PR DESCRIPTION
**Pull request by Xeeynamo**
Major clean-up about `Kkdf2MdlxParser`. I removed all the references to duplicate code such as the VPU simulator (now replaced by the modern `VifUnpacker`. All the classes used internally by Kkdf2MdlxParser are now private to encapsulate and isolate its logic. This will still return the same exact list of MeshDescriptor from #259 . The clean-up and refactoring reduces the code footprint by a lot.

One of the main reasons why I refactored the existing code was to understand better how to parse MDLX files.

### CODE REVIEW

**Comment by kenjiuno** [comment]
Thanks for refactoring! I'm going to check functionality of VertexMixer in VPU simulator.

2020-11-17_09h56_05

[modelsSummary.xlsx](https://github.com/Xeeynamo/OpenKh/files/5550558/modelsSummary.xlsx)

There is a list, and I will test some of them...

**Comment by kenjiuno** [comment]
It needs some fixes. I'll check it

2020-11-17_11h01_03

`ObjectId: 403`

al00.ard is modified. [al00.zip](https://github.com/Xeeynamo/OpenKh/files/5550823/al00.zip)

2020-11-17_11h04_42

[modelsSummary.xlsx](https://github.com/Xeeynamo/OpenKh/files/5550815/modelsSummary.xlsx)

**Comment by kenjiuno** [comment]
Sorry, this seems to be known bug of my code, and it is fixed (and not yet merged) in another branch 373dfd002b810e30643548cf73625d50a4d91c22

**Comment by kenjiuno** [comment]
Ok this will be better.

2020-11-17_11h40_31

@Xeeynamo Please merge this commit for fix: https://github.com/Xeeynamo/OpenKh/commit/7938d13dc740c95cec79ad76b515dbceaccb2c1a

```
git merge 7938d13dc740c95cec79ad76b515dbceaccb2c1a
```

**Comment by Xeeynamo** [comment]
This seems to work really well :D thank you for your patch.

PS. Azure Pipeline checks are failing

**Review by kenjiuno — APPROVED** [review]
Thanks! 👍

**Pull request merged**
