### PR TITLE
New input system

### PR DESCRIPTION
**Pull request by Xeeynamo**
Very inspired to the previous `InputManager`, this one is a re-modernisation of the previous one. You are still allowed to give a list of input devices, but all the logic to calculate the buttons repetition, released keys and triggered keys will be done after aggregating all the inputs rather than individually. Also I **FINALLY** created the interface `IInput`, so we can abstract the input implementation away from MonoGame. 

A part from the internal and technical changes, this is a list of features it brings to the table:
* Full analog support
* Pressed, Released, Triggered and Repeated keys
* Repeated keys are 1:1 with KH2
* Keyboard bindings can be, for now, configurable by editing the code

This will most likely break #418 as it relies on the old input system to move camera and player. Based on which one will be merged first, the other one needs to be rebased.

### CODE REVIEW

**Comment by Topaz-Reality** [comment]
Since you have mentioned it:
May I ask you to, if it would be appropriate, to include this PR inside of #418? It would be better to have all things gameplay related (Yes, even the input system) in that mega PR to avoid issues. Just in case.

**Comment by Xeeynamo** [comment]
> Since you have mentioned it:
> May I ask you to, if it would be appropriate, to include this PR inside of #418? It would be better to have all things gameplay related (Yes, even the input system) in that mega PR to avoid issues. Just in case.

I was thinking about that, but I prefer to have them reviewed and merged separately to have more continuous integration and detect potential bugs individually

**Comment by Rikux3** [comment]
I haven't had a chance to test it yet, but from looking at the code I don't see anything wrong with it.

**Comment by Xeeynamo** [comment]
I rebased the PR upon #418 as it was causing conflicts. I took the chance to add a smoother camera and character movement thanks to the analog values.

**Review by Truthkey — CHANGES_REQUESTED** [review]
I would recommend changing the inputs to "brand" agnostic. For example, Cross would be FaceDown.
Same would go for the rest of buttons.

**Comment by Xeeynamo** [comment]
> I would recommend changing the inputs to "brand" agnostic. For example, Cross would be FaceDown.
> Same would go for the rest of buttons.

Done 👍

**Review by Truthkey — APPROVED** [review]

**Comment by Rikux3** [comment]
Plays smoothly and works flawless with my DS4.

**Pull request merged**
