### PR TITLE
Add japanese support to KH2 Text Editor

### PR DESCRIPTION
**Pull request by Xeeynamo**

### CODE REVIEW

**Comment by Rikux3** [comment]
Support for special characters like `XI` or `III` isn't implemented right?

**Comment by Xeeynamo** [comment]
That is a really strong point. There is no support for those characters. I will fix it in few hours.

**Comment by Xeeynamo** [comment]
Are there not III, XI and XII in the JP font, am I right?

**Comment by Rikux3** [comment]
Doesn't look like it . I've attached the whole font map.

**Comment by Vladabdf** [comment]
I spotted III in the provided image. Fourth row, center-right.

**Comment by Rikux3** [comment]
@Vladabdf The characters in the first "block" (top-left) are interpreted as strings, so these are already implemented.

**Comment by Xeeynamo** [comment]
Done!

**Comment by Rikux3** [comment]
Opening text 1447 in sys.bar results in a crash in JapaneseSystemEncoder.cs::AppendEncodedChar
grafik

**Comment by Rikux3** [comment]
`XIII` also appears to render wrong

grafik

**Comment by Xeeynamo** [comment]
I swear that now is working 👀

**Comment by Rikux3** [comment]
I'm okay with that. The progress made in this branch is already big enough.

**Pull request merged**
