### PR TITLE
Added Luxord into Enemy List and changed 00battle.bin into decimals

### PR DESCRIPTION
**Pull request by 1234567890num**

### CODE REVIEW

**Comment by Truthkey** [comment]
Is there any reasoning for changing them to decimal?

**Comment by 1234567890num** [comment]
For consistency (and because you wrote that it's recommended to put everything in decimal [here](https://github.com/Truthkey/OpenKH_CodeGuidelines/blob/main/DocumentationFormatting.md) )

**Comment by Topaz-Reality** [comment]
Well, that is a little bit odd. Didn't we all agree to stay hexadecimal?
That guide linked contradicts what was discussed, doesn't it?

**Comment by Truthkey** [comment]
That's not an official guideline. It's just a proposal I made. Change offsets back to hex if you want this to be merged.

**Comment by 1234567890num** [comment]
What about the Enemy IDs? Are those better in hex or dec?

**Comment by Truthkey** [comment]
I'd say right now use the one it originally had. We're currently defining how documentation should be laid out.

**Comment by 1234567890num** [comment]
The offset has now been changed to hexadecimal. Only for KH2's 00batle.bin though.

**Review by Truthkey — APPROVED** [review]

**Pull request merged**
