### PR TITLE
WIP: Fix 4-bpp pixel order problem.

### LINKED ISSUE #223: 4-bpp IMGD issue
- _Windows 4-bpp bitmap_ and _PS2 4-bpp bitmap_ share same pixel order. No conversion is required: `0x12 0x34 0x56` is interpreted as `1 2 3 4 5 6`.
- However only **4-bpp unswizzled IMGD** is swapped: `0x12 0x34 0x56` is `2 1 4 3 6 5`

### PR DESCRIPTION
**Pull request by kenjiuno**
Still I need some tests for this.

Fix #223

### CODE REVIEW

**Comment by Vladabdf** [comment]
As of commit edec9c3 this fixes color swapping with 4bpp IMGZ images, but not IMGD. (Apologies for testing this so late!)

**Comment by kenjiuno** [comment]
> As of commit edec9c3 this fixes color swapping with 4bpp IMGZ images, but not IMGD. (Apologies for testing this so late!)

Hi @Vladabdf 
Did you find IMGD problem on ImageViewer? I have these test cases, and please let me know if there are missing testing patterns!


2020-11-17_13h54_29

[g4.zip](https://github.com/Xeeynamo/OpenKh/files/5551335/g4.zip)

**Comment by Vladabdf** [comment]
Ah, it does work! I must've done something wrong before, but all is well now.

**Review by Vladabdf — APPROVED** [review]
We finally have an converter for various image formats with a GUI! I'm so excited!!!

**Pull request merged**
