### PR TITLE
*Repack algorithm added

### PR DESCRIPTION
**Pull request by MiguelQueiroz010**
Not all optimized, but works for repacking all .DAT partitions with respective files ordering.

### CODE REVIEW

**Review by MiguelQueiroz010 — COMMENTED** [review]
Reviewed commented code deletion.

**Review by Truthkey — APPROVED** [review]
I checked all your code and everything seems correct., but make sure to make all those protected variables you changed to public back to protected if possible

Great work!

**Review by MiguelQueiroz010 — COMMENTED** [review]
Concluded review on modifiers, not all modifiers on public could be changed back to protected, almost everyone of them are used as public to other classes.

**Comment by Delta-473** [comment]
Ready to merge?

**Comment by MiguelQueiroz010** [comment]
Now it is ready to merge!

**Pull request merged**
