### PR TITLE
Soraiko/anb-lister

### PR DESCRIPTION
**Pull request by Soraiko**
Anb Lister allows to reunite each ANB folder by world in separate MSETS with a copy of the corresponding MDLX in separate folders. Recommanded with Kenji's khkhxldmii viewer. Very convenient to find a specific animation among a thousand.

### CODE REVIEW

**Comment by Xeeynamo** [comment]
Since the chat we had on Discord, are you still confident to have this merged into master? Or do you prefer to polish the code a bit more before the merge?

**Comment by Rikux3** [comment]
As this issue approaches it's one year anniversary without changes, should we close it?

**Comment by Xeeynamo** [comment]
I am preparing cake and decorations 🎂🎈🥳

**Comment by Rikux3** [comment]
grafik

Alright, closing this one...

**Pull request closed without merging**
