### PR TITLE
Changes the bar file type 2 to OtherData

### PR DESCRIPTION
**Pull request by gjgfuj**
Changes the bar file type 2 to OtherData which provides more clarity since these files don't have a known type although they may generally be lists.

### CODE REVIEW

**Comment by Xeeynamo** [comment]
I was thinking about it and `Binary` might be more appropriate than `OtherData`

**Comment by Topaz-Reality** [comment]
> I was thinking about it and `Binary` might be more appropriate than `OtherData`

Binary does not fit this description. I think 'list' already suits it as well as it can.

**Comment by gjgfuj** [comment]
type 0x01 is for BAR files. so the existing Binary type is a misnomer too. Binary is a solid name too, and that'd be perfectly valid if that's what you'd wish to change it to.

**Comment by Topaz-Reality** [comment]
Upon further inspection, the list of names used in the BAR editor need to be refined and renewed.
I propose for this PR's closure, and creation of a project/issue/request where the list is renewed in a way that all collaborators can agree upon and that it would be accurate to the game.
I won't be closing the PR myself, however.

**Pull request closed without merging**
