### PR TITLE
Implement exports in Kh2SystemEditor

### PR DESCRIPTION
**Pull request by kenjiuno**
2020-07-25_22h17_31

2020-07-25_21h59_31

### CODE REVIEW

**Comment by kenjiuno** [comment]
I have only KH2 Japanese and KH2FM, thus I cannot verify whether text output is good or not. Please someone test it.

2020-07-25_21h49_32

2020-07-25_22h25_18

**Comment by kenjiuno** [comment]
I guessed that UCM (universal character modifier) discussed at discord may be associated with `Id` of item table. Thus exporting item list should help knowing about ARD file structure. Just I guessed.

**Comment by kenjiuno** [comment]
Copy encoding idea from Place Editor:

2020-07-26_22h11_00

Export seems to be ok too:

2020-07-26_22h09_33

**Comment by kenjiuno** [comment]
Thanks for reviewing! I'll check it

**Comment by kenjiuno** [comment]
OK this will be better...

**Comment by Xeeynamo** [comment]
I did not know you had to duplicate the entire class to allow to export them as any format. I am sure that later on a common solution will be found and we can refactor it. For now, I will be happy to merge the changes!

**Pull request merged**
