### PR TITLE
Fix JapaneseSystemDecode table

### PR DESCRIPTION
**Pull request by kenjiuno**
OpenKh is great project!
I'll just fix some of Japanese errors...

Before

2020-02-04_00h31_36

After

2020-02-04_00h35_24

However there are still some transcription errors...

I don't know how to fix fontimage mismatch, for now:

2020-02-04_00h48_40

Full text would be better with following output:

```
Str000 Num 00003f34 Off 00000238
待っていたよ

Str001 Num 00003f35 Off 00000240
彼に会って来た[14 59 00]
〆
　[14 78 00]
〆
彼は君に良く似ている

Str002 Num 00003f36 Off 00000262
おまえは？

Str003 Num 00003f37 Off 00000268
抜け殻－－[14 83 00]
〆
いや　これが本来の姿か

Str004 Num 00003f38 Off 00000282
名前を聞いたんだ

Str005 Num 00003f39 Off 0000028d
そんなものに意味はない[14 78 00]
〆
　[14 50 00]
〆
君はどうだ？[14 94 00]
〆
本当の名前を覚えているのか？

Str006 Num 00003f3a Off 000002c1
俺の本当の名前は－－

Str007 Num 00003f3b Off 000002d0
行き止まりか

Str008 Num 00003f3c Off 000002d9
うん

Str009 Num 00003f3d Off 000002dc
おろせよもう歩ける

Str010 Num 00003f3e Off 000002e7
なんだか－－[14 84 00]
〆
俺も闇の世界に染まってきたかな

Str011 Num 00003f3f Off 00000306
リク！

Str012 Num 00003f40 Off 0000030b
これが今の俺にふさわしい－－[14 f0 00]
〆
これが真実の世界－－[14 aa 00]
〆
もしそうなら－－[14 71 00]
〆
ここで闇に溶けてしまうのもいいかもな

Str013 Num 00003f41 Off 00000352
リク－－

Str014 Num 00003f42 Off 00000358
世界は光と闇でできている[14 88 00]
〆
　[14 67 00]
〆
俺たちは闇になるのさ

Str015 Num 00003f43 Off 0000037e
そうだな－－[14 76 00]
〆
世界は－－[14 8a 00]
〆
光の世界はもう大丈夫だもんな[14 d8 00]
〆
カイリや王様たちがいるし

Str016 Num 00003f44 Off 000003bb
そういうこと[14 42 00]
〆
　[14 96 00]
〆
なあ　ソラ[14 6c 00]
〆
悪いけど俺を波打ち際まで
引きずってくれないか？

Str017 Num 00003f45 Off 000003f3
波の音だけは同じだな

Str018 Num 00003f46 Off 00000401
続きがあるんだ－－[14 8b 00]
〆
俺がおまえより上だと思ってた話の

Str019 Num 00003f47 Off 00000424
ん？

Str020 Num 00003f48 Off 00000427
本当は－－[14 5f 00]
〆
ソラ　おまえがうらやましかった

Str021 Num 00003f49 Off 00000443
なんで？

Str022 Num 00003f4a Off 00000448
おまえみたいに
心のままに生きられたら[14 e4 00]
〆
楽しいだろうなって

Str023 Num 00003f4b Off 0000046c
これでも悩みはたくさんあるんだけどな

Str024 Num 00003f4c Off 00000480
たとえば？

Str025 Num 00003f4d Off 00000486
リクみたいになりたいとか

Str026 Num 00003f4e Off 00000494
そうか－－[14 c7 00]
〆
確かに俺になれたら
とても良いことがあるな[14 eb 00]
〆
おまえには絶対できないことだ

Str027 Num 00003f4f Off 000004ca
なんだよ　それ

Str028 Num 00003f50 Off 000004d2
ソラの友達でいられる

Str029 Num 00003f51 Off 000004e0
それなら－－[14 6b 00]
〆
俺は俺のままでいいや[14 97 00]
〆
リクには絶対できないことがあるから

Str030 Num 00003f52 Off 0000050f
ソラ？

Str031 Num 00003f53 Off 00000514
ん？

Str032 Num 00003f54 Off 00000517
たぶんおまえ宛てだ

Str033 Num 00004cad Off 00000522
この世界のどこかにいるあなたへ[14 d2 00]
〆
すべての悲しみが消えるようにとか[14 be 00]
〆
すべての心がつながるようにとか

Str034 Num 00004cae Off 0000055e
願うだけでは届かない想いを叶えるために[14 dc 00]
〆
私は進もうと思っています

Str035 Num 00004caf Off 00000589
新しい旅立ちは　意外に簡単なことかもしれない[14 2c 01]
〆
もしかしたらそれは　もう始まっているのかもしれない[14 04 01]
〆
この空がつなぐ世界で[14 a0 00]
〆
辿り着く場所は一緒だと信じています

Str036 Num 00004cb0 Off 000005f1
光だ

Str037 Num 00004cb1 Off 000005f5
光への扉－－

Str038 Num 00004cb2 Off 000005fe
一緒に行こう

Str039 Num 00004cb3 Off 00000607
ああ

Str040 Num 00004cb4 Off 0000060a
ソラ！　リク！

Str041 Num 00004cb5 Off 00000614
ただいま

Str042 Num 00004cb6 Off 00000619
おかえり

Str043 Num 00004cb7 Off 0000061e
何も変わってないな

Str044 Num 00004cb8 Off 0000062a
うん　何も変わらない

Str045 Num 00004cb9 Off 00000637
小さい世界だ

Str046 Num 00004cba Off 00000641
でも　世界は広かった

Str047 Num 00004cbb Off 0000064f
ああ

Str048 Num 00004cbc Off 00000652
でさ　結局　光への扉って何だったんだろう？

Str049 Num 00004cbd Off 0000066d
ここ

Str050 Num 00004cbe Off 00000670
ここ？

Str051 Num 00004cbf Off 00000674
ああ　どこにでもあるって事だよ

Str052 Num 00004cc0 Off 00000685
ソラ！[14 5a 00]
〆
リク！

Str053 Num 00004cc1 Off 00000692
どうしたんだよ？

Str054 Num 00004d1e Off 0000069b
これ

Str055 Num 00004d1f Off 0000069e
王様から？！

Str056 Num 00004d83 Off 000006a7
この世界のどこかにいるあなたへ－－

Str057 Num 00004d84 Off 000006bb
すべての悲しみが消えるようにとか
すべての心がつながるようにとか[14 90 01]
〆
願うだけでは届かない想いを叶えるために
私は進もうと思っています

Str058 Num 00004d85 Off 0000070a
新しい旅立ちは
意外に簡単なことかもしれない[14 22 01]
〆
もしかしたらそれは
もう始まっているのかもしれない

Str059 Num 00004d86 Off 00000746
この空がつなぐ世界で
辿り着く場所は一緒だと信じています

Str060 Num 00004d87 Off 0000076c
<17>
O伝説に現れるキーブレードは
大きな力を秘めているという

Str061 Num 00004d88 Off 00000794
<17>
Oキーブレードを持つ者が
世界を救ったとも[14 64 00]
〆
逆に世界に混沌をもたらした
とも伝えられている

Str062 Num 00004d89 Off 000007d5
<17>
Oキーブレードとは
いったいなんなのか[14 5a 00]
〆
鍵－－　すなわち扉を開く力

Str063 Num 00004d8a Off 00000803
<17>
O　　　　　　　　　　　キーブレードマスター
　

Str064 Num 00004d8b Off 00000821
<17>
O　失われたふたつ　　　　　　　　　　　　　　　　　

Str065 Num 00004d8c Off 0000083f
<17>
O　ゼアノートの記憶　　　　　　　　　　　　　　　　
　

Str066 Num 00004d8d Off 00000861
<17>
O　追跡者　　　　　　　　　　　　　　　　　　　　　

Str067 Num 00004d8e Off 00000881
<17>
O　　　　　　　　キーブレード戦争

Str068 Num 00004d8f Off 0000089a
<17>
O全ては－－

Str069 Num 00004d90 Off 000008a3
眠りからの誕生
```

### CODE REVIEW

**Comment by kenjiuno** [comment]
Sorry I forgot about SYS table...
I have just overwritten your SYS table with EVT table.
I need to fix this...

**Comment by kenjiuno** [comment]
@Xeeynamo Thanks for checking changes!
I have implemented JapaneseEventDecode/Encode as you suggested.
JapaneseSystemDecode will keep previous functionality.

I believe that I have fixed the broken part broken by me ;)

`sys.bar` with `System font` (good choice)

2020-02-04_01h26_09

`sys.bar` with `Event font` (wrong choice)

2020-02-04_01h33_13

`es.bar` with `Event font` (good choice)

2020-02-04_01h32_49

`es.bar` with `System.font` (wrong choice)

2020-02-04_01h32_35


> I believe that @Rikux3 was working on something very similar no long ago.

I'm sorry if I interfere your working for Japanese part...

**Comment by Rikux3** [comment]
@kenjiuno No need for apologizing! I'm glad that someone who fluently speaks japanese is fixing this issue, because i was mostly doing guess-work. Happy to have you contribute here 😁

**Comment by Rikux3** [comment]
I've also started to work on the EVT encoder, like Xeeynamo already mentioned. It's on the [jpfont-evt](https://github.com/Xeeynamo/OpenKh/tree/feature/jpfont-evt) branch.

**Comment by kenjiuno** [comment]
> I've also started to work on the EVT encoder, like Xeeynamo already mentioned. It's on the [jpfont-evt](https://github.com/Xeeynamo/OpenKh/tree/feature/jpfont-evt) branch.

Oh... I have recognized that you have already done your EVT decoder. ;)
I'll close this pr, and keep your good work!

**Pull request closed without merging**
