### PR TITLE
Tools/ddd rbin

### PR DESCRIPTION
**Pull request by thamstras**
DDD rbin extraction

based on info from: https://forum.xentax.com/viewtopic.php?f=10&t=9884&sid=7c58553d29dcad66cebddfb3689f4da7&start=15#p100644

### CODE REVIEW

**Comment by thamstras** [comment]
Original LZovl/BLZ decompression code from: https://www.gbadev.org/tools.php?showinfo=1439

**Comment by thamstras** [comment]
The code is still a bit messy and probably doesn't quite do enough error checking, but we can now extract single files, entire rbins or entire folders of rbins.

**Comment by Truthkey** [comment]
> The code is still a bit messy and probably doesn't quite do enough error checking, but we can now extract single files, entire rbins or entire folders of rbins.

Are you planning to continue working on this? If you don't, I'll merge it.

**Comment by thamstras** [comment]
I put in some more descriptive error messages and added some documentation. That'll probably do.

**Review by Truthkey — APPROVED** [review]

**Pull request merged**
