### PR TITLE
Add OpenKh.Command.MapGen

### PR DESCRIPTION
**Pull request by kenjiuno**
An incomplete `.map` file builder command line.

[newMap.zip](https://github.com/Xeeynamo/OpenKh/files/4975236/newMap.zip)

```
.
├── .editorconfig
├── images
│   ├── 256x128.imd
│   ├── 256x128.png
│   ├── ceil.imd
│   ├── ceil.png
│   ├── east.imd
│   ├── east.png
│   ├── floor.imd
│   ├── floor.png
│   ├── north.imd
│   ├── north.png
│   ├── south.imd
│   ├── south.png
│   ├── west.imd
│   └── west.png
├── mapdef.yml
├── sparse.blend
├── sparse.fbx
└── sparse.map
```

`sparse.blend` is better with Blender v2.82a or later.

fbx is exported from `sparse.blend` with Blender export.

```bat
OpenKh.Command.MapGen.exe sparse.fbx
```

This will build `sparse.map`

When export be sure `Up = Y Up` and `Forward = Z Forward`

image

### CODE REVIEW

**Comment by kenjiuno** [comment]
Ok it will be better

**Comment by Disgustor** [comment]
Hi, no matter what I do, I get a consistent error.
`WARN File not found of material "mtl_0_30000_1b00", or error thrown. Using fallback image instead.`

Every viewer and editor I use to view the attached file gives me no errors while viewing the object with its materials. Could you please take a look when you have the time? Thanks.
[map_test.zip](https://github.com/Xeeynamo/OpenKh/files/5010888/map_test.zip)

**Comment by kenjiuno** [comment]
Thanks.

I haved fixed some problems:

- overflow/underflow error on negative UV coordinates. Usually expanding it (0.0 ~ 1.0) to 0 ~ 4095. Currently it can expand -8.0 ~ 8.0 to -32767 ~ 32767. Clamping range from -32768 to 32767. I'm not sure if this workaround works well.
- warning when it relies on diffuse texture input filepath inside 3D model data. It is now extracted with debug message: `DEBUG The mesh "" material "mtl_1_30000_4000_r" has filepath "images\tex_1_30000_4000_r.png" for diffuse texture. It will be associated with material's fromFile2.`

And please place this `mapdef.yml` attached in `mapdef.zip`:

```yml
imageDirs:
- 'images'

skipConversionIfExists: true
```

[mapdef.zip](https://github.com/Xeeynamo/OpenKh/files/5011637/mapdef.zip)

It will work better against previous version...

**Comment by kenjiuno** [comment]
Some parts need updates 📝

- [ ] copy imageDirs interpretation from https://discord.com/channels/409140906625728532/575294743852875787/739368742575931453
- [ ] add applyMatrix description
- [ ] COCT/DOCT optimization

**Comment by Tomk1004** [comment]
Hi, the map generator works incredibly, however, I don't know if it's an issue on my end, but the red channel on the vertex colors seems to be much higher than normal.
red channel
red channel2

 (the maps in question are directly from Murugo's KH1 Map viewer, and exported again from Maya. also, don't worry about the transparency or tiling on the model, I just didn't set the bytes to enable them)

**Comment by kenjiuno** [comment]
Thanks, I'll it later!

**Comment by kenjiuno** [comment]
@Tomk1004 

Please try latest version. It will work better. I tried `pc00_04.fbx` without (remove) `mapdef.yml` file.

2020-08-04_22h07_53

**Comment by kenjiuno** [comment]
Some updates:

## maxColorIntensity and maxAlpha

```yml
maxColorIntensity: 64
maxAlpha: 255

materials:
  - name: void
    ignore: true
```

[diagnoal.zip](https://github.com/Xeeynamo/OpenKh/files/5022437/diagnoal.zip)

default (maxColorIntensity=128, maxAlpha=128):

2020-08-04_22h37_15

```yml
maxColorIntensity: 64
maxAlpha: 255
```

2020-08-04_22h36_53


## transparent

```yml
skipConversionIfExists: true

materials:
  - name: void
    ignore: true
  - name: floor
    transparentFlag: 1
  - name: blue
    transparentFlag: 0
```

[transparent.zip](https://github.com/Xeeynamo/OpenKh/files/5022561/transparent.zip)

2020-08-04_23h09_59


## texture clamp mode

```yml
textureOptions:
  # addressU
  # addressV are one of: 'Repeat', 'Clamp', 'RegionClamp', 'RegionRepeat'
  addressU: 'Repeat'
  addressV: 'Repeat'
```

[addr.zip](https://github.com/Xeeynamo/OpenKh/files/5022682/addr.zip)

floor

Clamp:

2020-08-04_23h25_47

Repeat:

2020-08-04_23h26_42

RegionClamp:

2020-08-04_23h27_15

RegionRepeat:

2020-08-04_23h27_50

_This is bug of MapGen_

**Comment by Xeeynamo** [comment]
Tom and Disgustor made the tool approval 😄 congratulations for your amazing work, we never expected to have custom maps in Kingdom Hearts II 👏 .

As soon as you mark this pull request as Ready, I will do a short code review if needed. We believe that, even if the tools are not yet perfect, they can be improved later on anyway.

**Comment by kenjiuno** [comment]
Thank you for great help! I couldn't achieve this without your help and support of OpenKh project!

I'll now mark this pull request as ready, and please review this. I'll fix if there are problems.

**Comment by kenjiuno** [comment]
Thank you very much! 👍

**Comment by Disgustor** [comment]
Hi, I narrowed down the problem with the game lagging to the DOCT file allowing everything to be shown at once. I have a theory that this is also what's causing the transparency flag to crash the game when set on large maps, because it doesn't happen if the map is smaller. It only causes a crash if the map is too large. Optimizing the DOCT file could potentially fix both problems, but I'm not certain.

Thank you so much for your hard work! Having custom maps is a dream come true.

**Comment by Disgustor** [comment]
Here's an image with the transparency flag working, it only works if only a small part of the map is rendered. I just wanted to confirm it again.

https://cdn.discordapp.com/attachments/575294743852875787/740855182480506890/unknown.png

**Comment by Disgustor** [comment]
I discovered a lot of the flags in the COCT file. Here's what I found:

struct flagsCOCT {

	ubyte partyStand : 1;
	ubyte entityFallOverride : 1;
	ubyte unkFallFlag1 : 1; //seems to only affect the player
	ubyte unkFallFlag2 : 1;
	ubyte partyCollide : 1;
	ubyte objectCollide : 1; //affects enemies and field objects like the skateboard
	ubyte unk01_1 : 1;
	ubyte attackCollide : 1;
	
	ubyte unk02_1 : 1;
	ubyte unk02_2 : 1;
	ubyte ledgeGrab : 1;
	ubyte dispBarrier : 1;
	ubyte dispMessage : 1;
	ubyte unk02_3 : 1;
	ubyte unk02_4 : 1;
	ubyte unk02_5 : 1;
	
	ubyte unk03;
	ubyte unk04;
}

**Comment by kenjiuno** [comment]
Thanks Disgustor!
I'm working on DOCT splitting. I'll let you know when it is ready.
And thanks for COCT flags documentation. I'll append your research to [coct](https://openkh.dev/kh2/file/type/coct.html)!

**Pull request merged**
