### PR TITLE
Add GUI tool to manage IDX and IMG files

### PR DESCRIPTION
**Pull request by Xeeynamo**
This adds a GUI version of `OpenKh.Command.IdxImg`, which would simplify the file extraction process by a lot for new users.
I personally found this tool useful whenever I wanted to extract just a single file, without being forced to re-extract the entire game.

image

NOTE: This version does not include the "Inject" feature from the command line.

### CODE REVIEW

**Comment by kenjiuno** [comment]
OK I could extract file directly from KH2.IDX/KH2.IMG!

2020-08-05_21h37_36

I noticed (or I have completely forgotten) that `eh18.map` is stored under `000eh.idx`.
Because modern file extractors can merge them into single folder tree, it tends to forgot about it.

**Comment by kenjiuno** [comment]
`Export and merge all files from KH2.idx` is great feature!

2020-08-05_22h06_17

It can extract all known files from KH2.idx without command line knowledge and sub-index file (e.g. `000tt.idx`) thing!

2020-08-05_22h11_37

**Comment by Xeeynamo** [comment]
I solved the merging conflicts. Please let me know if I need to change something before to approve this.

**Comment by kenjiuno** [comment]
This works flawlessly! 👍

**Pull request merged**
