### PR TITLE
Update demo_debug.md with TEXANM menu option

### PR DESCRIPTION
**Pull request by Tomk1004**
TEXANM menu option

### CODE REVIEW

**Comment by Xeeynamo** [comment]
Hi Tom, could you add slightly more details about TEXANM menu option? If it's worth it, it would be cool to have a screenshot or two that sums up its functionalities

**Comment by Tomk1004** [comment]
good idea, I'll add that and try and document some more menus as to not clutter the PRs

**Comment by Xeeynamo** [comment]
Are there plans to continue this?

**Comment by Tomk1004** [comment]
I will, sorry about that, I just need to figure out how to add images to a
markdown doc

**Comment by Vladabdf** [comment]
Reference the text editor guide as I included various images in it.

**Comment by Topaz-Reality** [comment]
@Tomk1004 Can we have any updates on this?

**Comment by Vladabdf** [comment]
Closing due to deprecation by a future PR.

**Pull request closed without merging**
