### PR TITLE
Add editing actions to ImageViewer

### PR DESCRIPTION
**Pull request by kenjiuno**
Add editing actions:

2020-08-12_15h03_11

### CODE REVIEW

**Comment by kenjiuno** [comment]
This pull request is under development.
If someone feels this useful, please share your ideas!

**Comment by Xeeynamo** [comment]
The features you're adding are very interesting and we needed similar logic to this tool :) 
Are you going to put those actions inside a sub-menu later on? (eg. `Edit` menu)

**Comment by Vladabdf** [comment]
For what it's worth, I would prefer these buttons outside of the menu in this instance. Having them easily presented and accessible for such a simple tool is ideal in my opinion. Otherwise, so far it looks like a great addition to have!

**Comment by kenjiuno** [comment]
This time I have put editors under Edit menu.

2020-08-03_09h11_25

In the future, it will be better if it can implement thumbnail list (and action menu too) like the following design sample:

2020-08-03_09h21_41

**Comment by kenjiuno** [comment]
This will be better

**Comment by kenjiuno** [comment]
Thanks for reviewing this!
I'll try to fix it by using assembly reference.

**Pull request merged**
