### PR TITLE
Fix invalid file usage for WinShell programs.

### LINKED ISSUE #430: Unable to delete IMD files from Windows Explorer
**OpenKH Build**
1402

**OpenKH Program**
WinShell

**Describe the Bug**
Unable to delete IMD files from Windows Explorer

**To Reproduce**
Extract few images with Image Viewer from an IMZ as IMD then try to delete those IMD.

**Expected behavior**
IMDs should be deleted

**Screenshots**
image

**Additional context**
openkh is c00l

### PR DESCRIPTION
**Pull request by Topaz-Reality**
For some reason, fixes #430.
Needs testing on other machines to confirm.

### CODE REVIEW

**Review by Delta-473 — COMMENTED** [review]
Not tested but you closing the streams now. :)

**Comment by Topaz-Reality** [comment]
It **should** close them since I am using a `using` statement. But for some reason it... didn't.
Again, though. Needs testing on other hardware.

**Comment by Xeeynamo** [comment]
> But for some reason it... didn't.
Are you sure it is the case and that the bug might not be somewhere else?

**Comment by Xeeynamo** [comment]
So, apparently the bug might be in `IMDThumbnail` where the object `SelectedItemStream` is not disposed? https://github.com/dwmkerr/sharpshell/issues/339

**Comment by Topaz-Reality** [comment]
> So, apparently the bug might be in `IMDThumbnail` where the object `SelectedItemStream` is not disposed? [dwmkerr/sharpshell#339](https://github.com/dwmkerr/sharpshell/issues/339)

You did not file an issue for IMDThumbnail, but rather, IMZExtract.
I have tested all four with this change in this case. However, I will look into this.
SelectedItemStream does not affect IMDs in IMZExtract.

**Comment by Topaz-Reality** [comment]
Addressed it just in case.

**Review by Xeeynamo — APPROVED** [review]

**Pull request merged**
