### PR TITLE
Doc/contributing

### PR DESCRIPTION
**Pull request by Xeeynamo**
Any feedback?

### CODE REVIEW

**Comment by Topaz-Reality** [comment]
Seems acceptable as-is. But I think the shortened names should be all capital, ignorting PascalCase (OpenKh.Kh2 to OpenKH.KH2). I just, feel uncomfortable with the shortened names being typed like that. Still, just a nitpick. The rest seems acceptable.

**Comment by Rikux3** [comment]
> 
> 
> Seems acceptable as-is. But I think the shortened names should be all capital, ignorting PascalCase (OpenKh.Kh2 to OpenKH.KH2). I just, feel uncomfortable with the shortened names being typed like that. Still, just a nitpick. The rest seems acceptable.

Normally i would agree on that. But for OpenKh i'm down for Pascal casing, because, at least for me, it signalizes a change, a fresh new start so to speak (and not to forget the already existing "OpenKH" repository).

**Comment by Xeeynamo** [comment]
> > Seems acceptable as-is. But I think the shortened names should be all capital, ignorting PascalCase (OpenKh.Kh2 to OpenKH.KH2). I just, feel uncomfortable with the shortened names being typed like that. Still, just a nitpick. The rest seems acceptable.
> 
> Normally i would agree on that. But for OpenKh i'm down for Pascal casing, because, at least for me, it signalizes a change, a fresh new start so to speak (and not to forget the already existing "OpenKH" repository).

Camel Case and Pascal Case applies to acronyms too (eg. Xml instead of XML, Id, ChIndex, etc.). Since the entire .Net Framework uses Pascal Case, I think that makes perfectly sense to name namespaces as OpenKh.Kh2 instead of OpenKH.KH2 (even if it looks weird, it is consistent).

**Comment by Xeeynamo** [comment]
I finished to polish the documents of this Pull Request. Do you think that there is something more to add or modify to `README.md` or `CONTRIBUTING.md`? If yes, be free to append more commits to it.

If everything looks fine for you, just feel free to accept the pull request and merge it into master.

**Comment by Vladabdf** [comment]
I'll touch up on grammar a bit later, but for now it looks great. Merging

**Pull request merged**
